// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Saturn.Telegram.Db;

#nullable disable

namespace Saturn.Telegram.Db.Migrations
{
    [DbContext(typeof(SaturnContext))]
    [Migration("20260522000000_AddIsBotToMessages")]
    partial class AddIsBotToMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.AiAgentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.HasKey("Id")
                        .HasName("pk_ai_agents");

                    b.ToTable("ai_agents", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.ChatEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AiAgentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ai_agent_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_chats");

                    b.HasIndex("AiAgentId")
                        .HasDatabaseName("ix_chats_ai_agent_id");

                    b.ToTable("chats", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.GamePointsEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("UserId", "ChatId")
                        .HasName("pk_game_points");

                    b.ToTable("game_points", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.ImagePromptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("keywords");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.HasKey("Id")
                        .HasName("pk_image_prompts");

                    b.ToTable("image_prompts", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.KarmaChangeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Delta")
                        .HasColumnType("integer")
                        .HasColumnName("delta");

                    b.Property<long>("FromUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_user_id");

                    b.Property<long>("MessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("message_id");

                    b.Property<long>("ToUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id")
                        .HasName("pk_karma_changes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_karma_changes_created_at");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_karma_changes_from_user_id");

                    b.HasIndex("ToUserId")
                        .HasDatabaseName("ix_karma_changes_to_user_id");

                    b.ToTable("karma_changes", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.LogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<JsonDocument>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("message");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_logs_created_at");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_logs_source");

                    b.ToTable("logs", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.MessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bot");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("message_date");

                    b.Property<long?>("ReplyToMessageChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_chat_id");

                    b.Property<long?>("ReplyToMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("reply_to_message_id");

                    b.Property<string>("StickerId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("sticker_id");

                    b.Property<string>("Text")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id", "ChatId")
                        .HasName("pk_messages");

                    b.HasIndex("ChatId")
                        .HasDatabaseName("ix_messages_chat_id");

                    b.HasIndex("UserId", "ChatId")
                        .HasDatabaseName("ix_messages_user_id_chat_id");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.NamorevoGoreScoreEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("UserId")
                        .HasName("pk_namorevo_gore_scores");

                    b.ToTable("namorevo_gore_scores", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.OperationCallEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_at");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("OperationName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("operation_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_operation_calls");

                    b.ToTable("operation_calls", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.UserKarmaEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("UserId")
                        .HasName("pk_user_karma");

                    b.ToTable("user_karma", (string)null);
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.ChatEntity", b =>
                {
                    b.HasOne("Saturn.Telegram.Db.Entities.AiAgentEntity", "AiAgent")
                        .WithMany("Chats")
                        .HasForeignKey("AiAgentId")
                        .HasConstraintName("fk_chats_ai_agents_ai_agent_id");

                    b.Navigation("AiAgent");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.GamePointsEntity", b =>
                {
                    b.HasOne("Saturn.Telegram.Db.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_points_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.KarmaChangeEntity", b =>
                {
                    b.HasOne("Saturn.Telegram.Db.Entities.UserEntity", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_karma_changes_users_from_user_id");

                    b.HasOne("Saturn.Telegram.Db.Entities.UserEntity", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_karma_changes_users_to_user_id");

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.MessageEntity", b =>
                {
                    b.HasOne("Saturn.Telegram.Db.Entities.ChatEntity", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_chats_chat_id");

                    b.HasOne("Saturn.Telegram.Db.Entities.UserEntity", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messages_users_user_id");

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.NamorevoGoreScoreEntity", b =>
                {
                    b.HasOne("Saturn.Telegram.Db.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("Saturn.Telegram.Db.Entities.NamorevoGoreScoreEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_namorevo_gore_scores_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.UserKarmaEntity", b =>
                {
                    b.HasOne("Saturn.Telegram.Db.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("Saturn.Telegram.Db.Entities.UserKarmaEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_karma_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.AiAgentEntity", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.ChatEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Saturn.Telegram.Db.Entities.UserEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
